version: "3"

volumes:
  postgres_volume:
  rabbitmq_volume:

services:
  app:
    build:
      context: ./app/
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database

  web-proxy:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  database:
    image: postgres:15-alpine
  #  volumes:
  #    - postgres_volume:/var/lib/postgresql/data:owned
    ports:
      - "5432:5432"
    env_file:
      ./app/.env
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.13-management
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      ./app/.env
    restart: on-failure



